### PR TITLE
Add New SDKs & Code Samples

### PR DESCRIPTION
**Pull request by unicodeveloper**
- Add Python, Kotlin, Go, Ruby, PHP & Curl code samples
- Add link to view SDKs

### CODE REVIEW

**Comment by Cliftonz** [comment]
Two things,
1. The text moves with the size of the sdk, I find this very visually annoying. Since e are using tailwind on that div we should be able to set it as an absolute position from the top and stop that from happening.
2. I think the view SDK and Read Docs button should be switch as the user in this section is more likely to hit the left button over the right button as there is no color differentiation between them and the user will have already been clicking on the left which also puts them in a physiological predisposition to click the left button.
novufpage

**Comment by unicodeveloper** [comment]
Great point with the visual movement. Will look into it & switch the positions of the buttons.

**Comment by unicodeveloper** [comment]
@andrewgolovanov Please I need your help. Been trying to rectify the visual alignment. Can you help fix that? the recommendation by @Cliftonz

**Comment by unicodeveloper** [comment]
Optimizing for us getting this PR in. In another PR, we can fix the visual alignment. I moved the Go code section to the extreme right to ease the annoying visual alignment on the eyes.

**Review by scopsy — APPROVED** [review]

**Pull request merged**
