### PR TITLE
Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by sumitsaurabh927**
**Keep this PR open - some changes are yet to be made**

This PR makes the following changes:

- Add links to [this page](https://novu.co/hacktoberfest) on the main marketing site (Footers, nav-bar / menus)
- Change the upper banner to promote that we participating in Hacktoberfest
- Change everything to 2023
- Enable the countdown timer we had last year

## Changes remaining:

- [x]  Ensure that all the issues we have here sync with the hacktoberfest issues from our repos
- [x]  Swag pack images update
- [x]  A table that shows all the events and the dates
    - All events added but timezone yet to be updated

### CODE REVIEW

**Comment by sumitsaurabh927** [comment]
@andrewgolovanov Take a look here!

**Comment by unicodeveloper** [comment]
@sumitsaurabh927 Please can you specify what you'll like @andrewgolovanov to help with here? Please provide more clarity.

**Comment by sumitsaurabh927** [comment]
> @sumitsaurabh927 Please can you specify what you'll like @andrewgolovanov to help with here in a follow up comment? Please provide more clarity.

Sure thing!

@andrewgolovanov as mentioned in the 'Changed remaining' section [here](https://github.com/novuhq/website/pull/104#issue-1907263096), three things are remaining, out of which I need help on these two:
1. Swag pack images update - I've removed some swag images from the website as we no longer need them. However, the swag image needs an update as it still shows '2022'. More context in this [slack conversation](https://relayedhq.slack.com/archives/C02RT0NNP43/p1695298848703919?thread_ts=1694693151.086899&cid=C02RT0NNP43). 
> Note: The slack conversation also mentions contributors guide and a table for events. Those two have been done.
2. Issue sync: So we want only those issues to show up on the website which have been labelled 'Hacktoberfest' in our repos. Right now, issues are showing up arbitrarily.

**Comment by sumitsaurabh927** [comment]
Please @andrewgolovanov also tackle the timezone issue. I've added the time of these events in simple UTC time. Please ensure that it is in the format as it was last year

**Comment by andrewgolovanov** [comment]
> Please @andrewgolovanov also tackle the timezone issue. I've added the time of these events in simple UTC time. Please ensure that it is in the format as it was last year

@sumitsaurabh927 I don't see any changes that would affect timizone, so I can confirm that the time works on the same principle as last year

**Comment by sumitsaurabh927** [comment]
> > Please @andrewgolovanov also tackle the timezone issue. I've added the time of these events in simple UTC time. Please ensure that it is in the format as it was last year
> 
> @sumitsaurabh927 I don't see any changes that would affect timizone, so I can confirm that the time works on the same principle as last year

No, what I meant was this:
image
This is from last year.

I tried converting everything to UTC but it doesn't have these 'B', 'R', as in the event's list from last year

**Comment by andrewgolovanov** [comment]
@sumitsaurabh927 @unicodeveloper about the swag section, I suggest we temporarily hide it on the page, and once the design is ready we'll just put it back in.

What do you think about that?

**Comment by unicodeveloper** [comment]
That also works! @andrewgolovanov

**Comment by andrewgolovanov** [comment]
> And regarding the issues thing, the issues from our SDKs also need to show which I think isn't happening now @andrewgolovanov

Unfortunately for this we need a GitHub TOKEN to be able to work with [this endpoint](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-organization-issues-assigned-to-the-authenticated-user) or an extension to the current API functionality that would allow us to get this data, in case of data mining without authorization when we first get all repositories of an organization and then get per repository issues will lead us to query limits and error

I described [the problem in Slack](https://pixelpointworkspace.slack.com/archives/C02RT0NNP43/p1695394032037019?thread_ts=1694693151.086899&cid=C02RT0NNP43).

**Comment by andrewgolovanov** [comment]
> No, what I meant was this: image This is from last year.
> 
> I tried converting everything to UTC but it doesn't have these 'B', 'R', as in the event's list from last year

Oh, I see what you mean, unfortunately I don't have the exact schedule information to check these values, for that I need to know the exact time of each event and also in which time zone it takes place

as for the values A, B, R - if I understand correctly it refers to a certain time zone, [example of a converter](https://savvytime.com/converter/utc-to-a-b-r)

**Comment by sumitsaurabh927** [comment]
> > No, what I meant was this: image This is from last year.
> > I tried converting everything to UTC but it doesn't have these 'B', 'R', as in the event's list from last year
> 
> Oh, I see what you mean, unfortunately I don't have the exact schedule information to check these values, for that I need to know the exact time of each event and also in which time zone it takes place
> 
> as for the values A, B, R - if I understand correctly it refers to a certain time zone, [example of a converter](https://savvytime.com/converter/utc-to-a-b-r)

Here's the schedule:
```
const ITEMS = [
  {
    date: 'Oct 2',
    time: '03:00 PM (UTC)',
    utc: 'UTC-05:00, R',
    title: 'Hacktoberfest kick-off with Novu team',
    link: '',
  },
  {
    date: 'Oct 5',
    time: '04:00 PM UK time',
    utc: 'UTC-05:00, R',
    title: 'Livestream with Chakra UI / Panda CSS',
    link: '',
  },
  {
    date: 'Oct 6',
    time: '05:00 PM (UTC - 6:00 pm in WAT)',
    utc: 'UTC+02:00, B',
    title: 'Twitter spaces with Github stars Samson Goddy & Ruth Ikegah',
    link: '',
  },
  {
    date: 'Oct 10',
    time: '05:30 PM (in IST)',
    utc: 'UTC-05:00, R',
    title: 'Office hourse',
    link: '',
  },
  {
    date: 'Oct 12',
    time: '04:00 PM UK time',
    utc: 'UTC-05:00, R',
    title: 'Livestream with Appwrite',
    link: '',
  },
  {
    date: 'Oct 13',
    time: '06:00 PM (in WAT)',
    utc: 'UTC+01:00, A',
    title: 'Twitter Space with Alt School - Sultan & Jerry',
    link: '',
  },
  {
    date: 'Oct 31',
    time: '04:00 PM UK time',
    utc: 'UTC-05:00, R',
    title: 'C&S build night for Hacktoberfest, Night 5/5',
    link: 'https://www.meetup.com/Code-and-Supply/events/280000000/',
  },
  {
    date: 'Oct 17',
    time: '04:00 PM UK time',
    utc: 'UTC+01:00, A',
    title: 'Novu (Hacksquad) - How to build an auth system',
    link: '',
  },
  {
    date: 'Oct 19',
    time: '04:00 PM UK time',
    utc: 'UTC-05:00, R',
    title: 'Livestream with Sourcegraph',
    link: '',
  },
  {
    date: 'Oct 20',
    time: '06:00 PM (in WAT)',
    utc: 'UTC-05:00, R',
    title: 'Twitter Space with Francesco Ciulla',
    link: '',
  },
  {
    date: 'Oct 31',
    time: '06:30 PM in IST',
    utc: 'UTC-05:00, R',
    title: 'Office Hours',
    link: '',
  },
];
```

Ignore the `UTC` values in this array. The correct timings are the values for the `time` key

**Comment by sumitsaurabh927** [comment]
Also, @andrewgolovanov I've added a contribution guide modal in the hero section. Please style it and make it look coherent with the rest of the site

**Comment by andrewgolovanov** [comment]
> Also, @andrewgolovanov I've added a contribution guide modal in the hero section. Please style it and make it look coherent with the rest of the site

I've made style updates to the hero section and the formatting of the text in the modal window :sparkles:

**Review by andrewgolovanov — APPROVED** [review]

**Pull request merged**
